<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Nome</th>
            <th scope="col">Morada</th>
            <th scope="col">Telefone</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($medicos as $medico) { ?>
            <tr>
                <th scope="row"><?php echo "" ?></th>
                <td><?php echo $medico->getNome() ?></td>
                <td><?php echo $medico->getMorada() ?></td>
                <td><?php echo $medico->getTelefone() ?></td>
                <td>
                    <span><a style="color:blue" href="#">view user</a></span>
                    <span> | </span>
                    <span><a style="color:orange" href="#">edit user</a></span>
                    <span> | </span>
                    <span><a style="color:red" href="#">delete user</a></span>
                </td>
            </tr>
        <?php } ?>
    </tbody>
</table>